products_list:
    path: /products
    controller: App\Product\Application\Controller\ListProductCollection

product_show:
    path: /products/{slug}
    controller: App\Product\Application\Controller\ShowProduct

cart_show:
    path: /cart
    controller: App\Order\Application\Controller\ShowCart
